name: Protect Main Branch

on:
  push:
    branches:
      - main

jobs:
  block_direct_push:
    runs-on: ubuntu-latest
    steps:
      - name: Block direct push
        run: |
          echo "⛔ ¡No se permite el envío directo a la rama principal! Usa una solicitud de extracción."
          exit 1
