name: Protect Main Branch

on:
  push:
    branches:
      - main

jobs:
  notify_push:
    runs-on: ubuntu-latest
    steps:
      - name: Aviso de push a main
        run: |
          echo "⚠️ Alguien hizo un push directo a main. Se recomienda trabajar con Pull Requests. :)"

