name: Protect Main Branch

on:
  push:
    branches:
      - main

jobs:
  block_direct_push:
    runs-on: ubuntu-latest
    steps:
      - name: Detect and block manual pushes
        run: |
          echo "Pusher: ${{ github.actor }}"
          if [ "${{ github.actor }}" != "web-flow" ]; then
            echo "⛔ Push directo a main detectado. Solo se permiten Pull Requests."
            exit 1
          else
            echo "✅ Pull request merge detectado. Aprobado."
            exit 0
          fi
