name: Protect Main Branch

on:
  push:
    branches:
      - main

jobs:
  block_direct_push:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel if push is not a pull request merge
        run: |
          echo "Checking if this push came from a PR..."
          git log -1 --pretty=%B | grep -q "Merge pull request" && echo "✅ Pull request merge detectado." || (echo "⛔ Push directo a main detectado. Solo se permiten PRs." && exit 1)
